server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

spring:
  application:
    name: ai_receptionist
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/health_ai_receptionist
    username: postgres
    password: postgres
